<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.AspNetCore.Grid" Version="*" />
    <PackageReference Include="Syncfusion.AspNetCore.Themes" Version="*" />
  </ItemGroup>

</Project>
